version: '3.7'

volumes:
  web_data:
    external: true
    
services:
  nginix_loadbalancer:
        build:
            context: ./nginix_loadbalancer
        ports:
            - "8000:5000"
        links:
            - "app_1"
            - "app_2"
  app_1:
    build:
      context: ./app
    volumes:
      - type: volume
        source: web_data
        target: /Database
    environment:
      - DEBUG=1
  app_2:
    build:
      context: ./app
    volumes:
      - type: volume
        source: web_data
        target: /Database
    environment:
      - DEBUG=1
  