version: '3.7'

volumes:
  web_data:
    external: true
    
services:
  nginix_loadbalancer:
        build:
            context: ./nginix_loadbalancer
        ports:
            - "8000:5000"
        links:
            - "app_1"
            - "app_2"
  app_1:
    build:
      context: ./app
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - DEBUG=1
  app_2:
    build:
      context: ./app
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    environment:
      - DEBUG=1
  